# Example use:
# $ cd docker/orientdb
# $ docker build --name custom-orientdb .
# $ docker run docker run -itd -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root --name orientdb-nodejs-example custom-orientdb


FROM 		orientdb:2.2.0
MAINTAINER 	Mika Turunen <mika.turunen@ymail.com>


# TODO add your own personal configurations and flavours if you need them, if you don't, you don't have to use this
# 	   Dockerfile at all.
